export const THEMES = {
  warm: {
    name: "Warm Linen",
    bg: "#FAFAF9",
    surface: "#FFFFFF",
    border: "#E8E4DF",
    borderBottom: "#D4CFC9",
    textPrimary: "#1A1714",
    textSecondary: "#6B6560",
    textMuted: "#9B9590",
    topbarBg: "#FFFFFF",
    topbarBorder: "#F0EDE8",
    dark: false,
  },
  slate: {
    name: "Slate",
    bg: "#EEF2F7",
    surface: "#FFFFFF",
    border: "#C8D5E0",
    borderBottom: "#8FA5B5",
    textPrimary: "#1A2530",
    textSecondary: "#4A6070",
    textMuted: "#7A9AAA",
    topbarBg: "#FFFFFF",
    topbarBorder: "#D8E5F0",
    dark: false,
  },
  midnight: {
    name: "Midnight",
    bg: "#0F1020",
    surface: "#1A1C2E",
    border: "#2A2D45",
    borderBottom: "#0A0C1A",
    textPrimary: "#E8EAFF",
    textSecondary: "#A0A8CC",
    textMuted: "#6870A0",
    topbarBg: "#1A1C2E",
    topbarBorder: "#2A2D45",
    dark: true,
  },
  forest: {
    name: "Forest",
    bg: "#EAF2EC",
    surface: "#FFFFFF",
    border: "#B8D9C0",
    borderBottom: "#6B9E7A",
    textPrimary: "#1A2E1E",
    textSecondary: "#3A5E42",
    textMuted: "#6A9070",
    topbarBg: "#FFFFFF",
    topbarBorder: "#C8E4CC",
    dark: false,
  },
  rose: {
    name: "Rose",
    bg: "#FDF0F3",
    surface: "#FFFFFF",
    border: "#F0C8D4",
    borderBottom: "#D4849A",
    textPrimary: "#2E1018",
    textSecondary: "#6E3048",
    textMuted: "#A87088",
    topbarBg: "#FFFFFF",
    topbarBorder: "#F8D8E4",
    dark: false,
  },
  sand: {
    name: "Sand",
    bg: "#FAF5EB",
    surface: "#FFFFFF",
    border: "#E8D9B8",
    borderBottom: "#C4A96A",
    textPrimary: "#2A1E08",
    textSecondary: "#6A4E28",
    textMuted: "#9A7E58",
    topbarBg: "#FFFFFF",
    topbarBorder: "#F0E4C8",
    dark: false,
  },
  lavender: {
    name: "Lavender",
    bg: "#F5F0FF",
    surface: "#FFFFFF",
    border: "#D4C0F0",
    borderBottom: "#9070C8",
    textPrimary: "#1E1030",
    textSecondary: "#4E3870",
    textMuted: "#8070A8",
    topbarBg: "#FFFFFF",
    topbarBorder: "#E4D8F8",
    dark: false,
  },
  charcoal: {
    name: "Charcoal",
    bg: "#1E1E1E",
    surface: "#2A2A2A",
    border: "#3A3A3A",
    borderBottom: "#0A0A0A",
    textPrimary: "#F0F0F0",
    textSecondary: "#B0B0B0",
    textMuted: "#707070",
    topbarBg: "#2A2A2A",
    topbarBorder: "#3A3A3A",
    dark: true,
  },
} as const;

export type ThemeKey = keyof typeof THEMES;
export type Theme = (typeof THEMES)[ThemeKey];
export const DEFAULT_THEME: ThemeKey = "warm";
